/**
 * Generates `src/themes/palettes.ts`: one Material-You palette per theme,
 * computed by matugen from a source colour.
 *
 *   npm run generate:themes
 *
 * The output is committed, because CI has neither matugen nor any reason to
 * need it — re-run this only when a source colour changes or a token is added.
 *
 * `--dry-run` is not optional. Without it matugen also renders every template
 * in ~/.config/matugen and fires their post-hooks, which re-themes the machine
 * it runs on — hyprland, waybar, kitty, the lot — to whichever colour this
 * script happened to be looking at last.
 */

import { execFileSync } from "node:child_process";
import { writeFileSync } from "node:fs";
import { resolve } from "node:path";

interface Source {
  id: string;
  name: string;
  /** The colour matugen builds the palette from. */
  source: string;
  /** Hand-picked wallpaper colours, where the derived ones will not do. */
  wallpaper?: { logo: string; inner: string; outer: string };
}

const SOURCES: Source[] = [
  // The original wallpaper, drawn by hand: its logo is the source colour and
  // its gradient a little bluer than the logo. Keeping all three is what makes
  // the default theme look exactly like the site did before there were themes.
  {
    id: "blue",
    name: "Blue",
    source: "#0027a3",
    wallpaper: { logo: "#0027a3", inner: "#001c36", outer: "#000913" },
  },
  { id: "teal", name: "Teal", source: "#006b73" },
  { id: "rose", name: "Rose", source: "#a3004f" },
  { id: "amber", name: "Amber", source: "#a35a00" },
  { id: "green", name: "Green", source: "#2e7d00" },
];

const OUTPUT = resolve("src/themes/palettes.ts");

interface MatugenOutput {
  colors: Record<string, { dark: { color: string } }>;
  palettes: Record<string, Record<string, { color: string }>>;
}

function matugen(source: string): MatugenOutput {
  const json = execFileSync(
    "matugen",
    ["color", "hex", source, "--dry-run", "-m", "dark", "-j", "hex"],
    { encoding: "utf-8" },
  );
  return JSON.parse(json) as MatugenOutput;
}

function tokensFor({ source, wallpaper }: Source): Record<string, string> {
  const { colors, palettes } = matugen(source);
  const role = (name: string) => colors[name].dark.color;
  const tone = (palette: string, t: number) => palettes[palette][String(t)].color;

  return {
    primary: role("primary"),
    onPrimary: role("on_primary"),
    primaryContainer: role("primary_container"),
    onPrimaryContainer: role("on_primary_container"),
    // The bar fills secondary right beside primary at both of its ends, and
    // matugen's secondary (tone 80) sits at primary's tone with a near hue, so
    // the boundary between the two all but vanishes. Tone 90 keeps the hue and
    // separates the fills; on_secondary stays well above 4.5:1 on it.
    secondary: tone("secondary", 90),
    onSecondary: role("on_secondary"),
    tertiary: role("tertiary"),
    onTertiary: role("on_tertiary"),
    surfaceLowest: role("surface_container_lowest"),
    surface: role("surface_container"),
    surfaceHighest: role("surface_container_highest"),
    onSurface: role("on_surface"),
    onSurfaceVariant: role("on_surface_variant"),
    outline: role("outline"),
    outlineVariant: role("outline_variant"),
    // What the compositor draws around a window without focus: dark, but with
    // enough of the hue that the strip reads as one theme.
    borderIdle: tone("secondary", 25),
    // Tone 25 of the primary palette is where the original blue sits, so every
    // logo glows at the same depth. The sources themselves differ fivefold in
    // luminance, and drawn as they are, green and amber shouted over the rest.
    wallLogo: wallpaper?.logo ?? tone("primary", 25),
    wallInner: wallpaper?.inner ?? tone("primary", 10),
    wallOuter: wallpaper?.outer ?? tone("primary", 5),
  };
}

const themes = SOURCES.map((s) => ({ id: s.id, name: s.name, tokens: tokensFor(s) }));

const body = themes
  .map(({ id, name, tokens }) => {
    const lines = Object.entries(tokens).map(([k, v]) => `      ${k}: "${v}",`);
    return `  {\n    id: "${id}",\n    name: "${name}",\n    tokens: {\n${lines.join("\n")}\n    },\n  },`;
  })
  .join("\n");

writeFileSync(
  OUTPUT,
  `// Generated by scripts/generate-themes.ts — do not edit by hand.
// Re-run \`npm run generate:themes\` to change a palette.

export const PALETTES = [
${body}
] as const;
`,
);

console.log(`wrote ${themes.length} palettes to ${OUTPUT}`);
